### ISSUE TITLE
Do function input/output types matter?

### ISSUE THREAD

**Issue by uioporqwerty** [SVCE-ACM/A-December-of-Algorithms-2019#12]
For certain problems the input parameter types are apparent, however for others, such as 12-02, the input parameters could be integers, strings, etc. and the outputs could be boolean, strings, etc.. When this isn't clear can the input/output types be at the discretion of the implementer or should we get clarification on a per problem basis?

**Comment by mahavisvanathan** [comment]
Since all the problems are based on practical scenarios, the data types of the input and output are completely up to the implementer and their convenience. Feel free to assume any data type that will give you the most effective implementation. Just make sure the result in the specified format.

**Comment by K-Kraken** [comment]
### Issue resolved! :white_check_mark:
