### ISSUE TITLE
Misleading example on December-01?

### ISSUE THREAD

**Issue by atarv** [SVCE-ACM/A-December-of-Algorithms-2019#20]
Well, I might be wrong, but to my mind the 10th sevenish number should be 392, not 350.
Am I missing something or is the example in error?

My 10 first sevenish numbers: `1, 7, 8, 49, 50, 56, 343, 344, 350, 392`

**Comment by alirezaghey** [comment]
@atarv As I understand it, 350 is the correct 10th sevenish number.
The ten first sevenish numbers are as follows:
`1 (7^0), 7 (7^1), 8, 49 (7^2), 50, 56, 57, 343 (7^3), 344, 350`
You are missing `57`, which is `sum(1, 7, 49)`.
Admittedly, the wording of the problem and the given data are a little ambiguous.

**Comment by atarv** [comment]
Ah, I see. So a sevenish number is a sum of _any (positive) number_ of unique powers of 7. Is that correct?

**Comment by jyuvaraj03** [comment]
@atarv yes, your definition of the problem is right. The ten first sevenish numbers pointed out by @alirezaghey is the correct one.
