### ISSUE TITLE
[December 09] Regarding symbols

### ISSUE THREAD

**Issue by anshulsri12** [SVCE-ACM/A-December-of-Algorithms-2019#27]
* What all operations will be in the Function expression? e.g. power is given in the sample case, what else? Will there be square root, etc?
* And also specify the symbols that will be used for each operation.

**Comment by dhirajv2000** [comment]
The program can be limited to only one variable, considering the input sets have only singular elements and not ordered pairs. Therefore, the input expression can have one variable and several operators like(+,*,/,^). The operators can be limited to 4.
Example input functions:
f(x) : x+5
f(x) : (x^2)*6
f(y) : y-2
