### ISSUE TITLE
There is a typo into Sevenish Number problem

### ISSUE THREAD

**Issue by ArmanAirapetov** [SVCE-ACM/A-December-of-Algorithms-2019#28]
`> sevenish_number(10)
  350`
But I guess that _sevenish_number(10)_ must equal _392_. Or is that omission deliberate?

**Comment by mahavisvanathan** [comment]
Have a look at this issue for your reference : https://github.com/SVCE-ACM/A-December-of-Algorithms-2019/issues/20

**Comment by ArmanAirapetov** [comment]
@mahavisvanathan I am so sorry. It is my carelessness.
