### ISSUE TITLE
Optional requirement from exercise 13

### ISSUE THREAD

**Issue by milenamonteiro** [SVCE-ACM/A-December-of-Algorithms-2019#54]
I can't understand if the function for finding how many switches on `on` state is optional. In the README says:

- The task is to write `O(n)` and constant time functions to find how many switches are in the `on` state (two separate functions).
- [optional] Find the switch nos. that are in the 'on' state after n such iterations.

**Comment by SHRIRAM0509** [comment]
As you can see from the example given for Day 13, if the no. of switches is 5,
-> the no. of switches that are in the 'on' state are 2. (you'll be writing a function to find this given 'n')
-> The switch nos. in the on state are 1 and 4.(this is the optional part)
