### ISSUE TITLE
Are we allowed to send in a pull request without completing all the questions?

### ISSUE THREAD

**Issue by Nilesh2000** [SVCE-ACM/A-December-of-Algorithms-2019#67]
Though the README clearly states that we are supposed to send in a pull request only after completing all 31 algorithms, some contributors got their pull requests merged even without completing all the questions. Is that allowed?

**Comment by mahavisvanathan** [comment]
We offer three levels of certificates 

- **Beginner** (10 questions completed)
- **Intermediate** (20 questions completed)
- **Advanced**(All questions completed) 

You are allowed to send in a pull request without completing all the questions provided the number of questions you have solved is greater than the minimum required for a certificate. We are sorry for the discrepancy in the instructions. 
**_Happy coding!!_**

**Comment by Nilesh2000** [comment]
So, can I send in a pull request now?
I understand it's beyond the deadline, but I really would appreciate it if you guys could merge it.

**Comment by mahavisvanathan** [comment]
We are still accepting pull requests. Go ahead and send in a pull request with your completed solutions.

**Comment by Nilesh2000** [comment]
Thanks so much. I will send one right away.
